# Generated by Django 5.2.1 on 2025-05-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_cliente_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_inscripcion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.CharField(default='00000000', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='o', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('superuser', 'Superusuario'), ('profesor', 'Profesor'), ('cliente', 'Cliente')], default='cliente', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
    ]
