# Generated by Django 5.2.1 on 2025-06-07 01:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_cliente_first_name_remove_cliente_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(default=django.utils.timezone.now)),
                ('duracion_meses', models.PositiveIntegerField(choices=[(1, '1 mes'), (3, '3 meses'), (6, '6 meses')])),
                ('tipo_membresia', models.CharField(choices=[('libre', 'Pase libre'), ('2xsemana', '2 veces por semana'), ('3xsemana', '3 veces por semana')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cliente')),
            ],
        ),
    ]
